apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: accounts-cd-pipeline
spec:
  tasks:
    - name: cleanup
      taskRef: {name: cleanup}
    - name: git-clone
      runAfter: [cleanup]
      taskRef: {name: git-clone}
    - name: flake8
      runAfter: [git-clone]
      taskRef: {name: flake8}
    - name: nose
      runAfter: [flake8]
      taskRef: {name: nose}
    - name: buildah
      runAfter: [nose]
      taskRef: {name: buildah}
    - name: deploy
      runAfter: [buildah]
      taskRef: {name: kubernetes-deploy}
